USE CERTCONT_GI
GO
select distinct 
	[cc_area] AreaProyecto
	 ,case 
		  when [cc_area] = 'TP' then 'CESEL tiene una vasta experiencia en estudios y supervisión de construcción y rehabilitación de obras viales e importante en el sector aeronáutico.  tanto en el Perú como en otros países. Los proyectos desarrollados por CESEL a la fecha superan los 7500 km de carreteras, entre ellas la importante carretera Interoceánica Sur (Tramo 3). Debido a la naturaleza de la geografía peruana, estas obras involucran los más variados terrenos desde los desiertos de la costa, los escarpados y elevados Andes, hasta la lluviosa selva amazónica. En los últimos años CESEL está operando también en la agreste, fuertemente soleada y semiárida región del Chaco, Paraguay, con temperaturas que oscilan entre 46º y -7ºC; y en el altiplano de San Marcos, en Guatemala.'
		  when [cc_area] = 'EN' then 'CESEL tiene una experiencia muy importante en proyectos de generación, transmisión y distribución de energía eléctrica, así como en análisis de sistemas eléctricos. En los primeros años de la década del 80, supervisó las obras civiles y montaje electromecánico de la principal línea de transmisión realizada en el Perú en dicha década, la línea Mantaro - Pachachaca – Callahuanca (Lima) 220 kV, doble circuito y 300 km de longitud. Incluyó tres subestaciones eléctricas de 220 kV, una de ellas encapsulada GIS en SF6 y ubicada a la mayor altitud mundial para este tipo de equipos (4000 msnm). Recientemente es destacable su participación en la línea de interconexión centroamericana 230 kV, 1800 km SIEPAC; así como en los estudios de preoperatividad de la línea de transmisión Mantaro - Caravelí - Montalvo de 500 kV y 750 km de longitud y el diseño definitivo de sus subestaciones.'	
		  when [cc_area] = 'HI' then 'CESEL ha desarrollado una ininterrumpida e intensa actividad tanto en la planificación de recursos hídricos como en la elaboración de estudios y diseños así como en la supervisión de la construcción de grandes obras hidráulicas, abarcando todos los campos de la infraestructura hidráulica. Destaca su actuación en la mayor infraestructura hidroeléctrica diseñada en el Perú en la década del 90: el desarrollo hidroeléctrico San Gabán (450 MW).'	
		  when [cc_area] = 'AA' then 'CESEL siempre ha aplicado criterios ambientales en el desarrollo de sus proyectos, aún antes que en el Perú se establezcan las reglamentaciones específicas.  La gerencia de Asuntos Ambientales desarrolla servicios,en todos los ámbitos principales de actividad humana,instalaciones industriales e infraestructura. Cuenta con autorizaciones vigentes para realizar estudios ambientales en los sectores de agricultura, minería, energía, hidrocarburos, industria, carreteras, edificaciones, aeropuertos y obras portuarias, entre otros'			 
		  when [cc_area] = 'ED' then 'CESEL ha desarrollado proyectos de edificaciones muy importantes y de gran envergadura, como el Hospital Regional de Huancayo de 50 millones de dólares USA de inversión. Actualmente CESEL gerencia la construcción de la nueva ciudad de Morococha con 1050 viviendas y servicios múltiples para 5000 pobladores, una inversión de más de 50 millones de dólares, a más de 4000 m de altitud.'	
		  when [cc_area] = 'MI' then 'CESEL ha participado en los importantes proyectos mineros de Cobriza y Cerro Verde, así como en Yanacocha,Alto Chicama, Pierina, Antamina, Arcata, La Granja, etc.Recientemente ha participado en el desarrollo de la ingenieríabásica y la ingeniería de detalle y gestión de suministro de laAmpliación de la Planta Minera de Toquepala a 100.000 tpd'	
		  when [cc_area] = 'SA' then 'CESEL ha desarrollado estudios integrales de agua potable y alcantarillado de importantes centros urbanos del Perú, tales como Lima, Piura, Cajamarca y Villa El Salvador (750.000 habitantes); así como para la ciudad Puntarenas en Costa Rica; habiendo efectuado el diseño y supervisión de aproximadamente 4000 km de redes de agua potable y alcantarillado, así como de más de 45 plantas de tratamiento de agua y desagüe  '	
		  when [cc_area] = 'PU' then 'CESEL ha desarrollado la mayoría de los puertos fluviales de la amazonía peruana desde mediados de la década del 70, en que diseñó y supervisó la construcción de los puertos de Iquitos, Pucallpa y Yurimaguas. Su participación en los principales puertos marítimos de la costa peruana también ha sido muy importante, destacando el plan maestro de desarrollo al 2025 y el diseño detallado de la ampliación y modernización del Puerto del Callao para una inversión de más de 400 millones de dólares USA. Recientemente ha realizado la supervisión de la construcción y equipamiento del nuevo gran terminal de contenedores en la zona sur  del Puerto del Callao, para naves tipo “Panamax” con un muelle de 650 m y 2 amarraderos. Ha realizado el diseño y supervisión de obra de más de 35 puertos.'	
		  when [cc_area] = 'HP' then 'CESEL desarrolla servicios para la industria petrolera, en lo que se refiere a las instalaciones vinculadas tales como tanques de almacenamiento, tuberías, oleoductos, gasoductos, baterías, estaciones de bombeo, plantas de tratamiento, etc. Ha prestado servicios a las refinerías de La PampillaCESEL desarrolla servicios para la industria petrolera, en lo que se refiere a las instalaciones vinculadas tales como tanques de almacenamiento, tuberías, oleoductos, gasoductos, baterías, estaciones de bombeo, plantas de tratamiento, etc. Ha prestado servicios a las refinerías de La Pampilla y de Talara, entre otras instalaciones importantes. CESEL también desarrolla servicios en el campo de la petroquímica y refinerías para producción de biocombustiblesy de Talara, entre otras instalaciones importantes. CESEL también desarrolla servicios en el campo de la petroquímica y refinerías para producción de biocombustibles'	
		  when [cc_area] = 'MF' then 'CESEL desde fines de la década del 80 la empresa ha estado vinculada con el desarrollo del Metro de Lima. Inicialmente con la supervisión de parte de sus estructuras elevadas. Hace 10 años desarrollando el Estudio de la Red del Metro para las siguientes décadas, incluyendo estudios de demanda de transporte, seleccionando las 5 líneas iniciales, el marco institucional para su operación y administración, elaborando el Anteproyecto e ingeniería de la Línea 1, etc. Actualmente CESEL realiza la supervisión del diseño y de la construcción y montaje de los primeros 22 km del metro, en ruta elevada '	
		  when [cc_area] = 'SL' then 'CESEL ha diseñado y/o supervisado la construcción de un sinnúmero de importantes establecimientos de salud del Perú, como son el Hospital Regional de Huancayo (500 camas), el Hospital General de Belén (400 camas; ampliación y remodelación), Hospital Alberto Sabogal (157 camas) etc, incluyendo todos sus componentes especializados tal como centros quirúrgicos, centro obstétrico y neonatológico, hospitalización, unidad de cuidados intensivos, unidades de diagnóstico por imágenes, radioterapia, etc '	
		  when [cc_area] = 'GT' then 'CESEL realiza estudios de geología orientados a sustentar sus proyectos. Asimismo efectúa una gran diversidad de servicios de exploración geotécnica, tales como: perforación mediante el método de lavado (wash boring), ensayo de penetración estándar (SPT), ensayo de penetración dinámica de cono (CPT), ensayo de penetración dinámica ligera (DPL), auscultación de sondajes (Iwan Auger), registros mediante calicatas y trincheras, controles de compactación, ensayos de permeabilidad in-situ, ensayo de carga directa (Placa), estaciones geomecánicas, ensayo “Tilt Test”, instrumentación y monitoreo de piezómetros y de inclinómetros (para taludes inestables). Ensayos geofísicos: refracción sísmica, Downhole, sondajes eléctricos verticales. Estudios geotécnicos para cimentaciones (superficiales y profundas), túneles, estabilidad de taludes, presas, carreteras, canteras, líneas de transmisión, subestaciones, centrales hidroeléctricas, lagunas de oxidación, etc.'	
		  when [cc_area] = 'CT' then 'CESEL en este rubro desarrolla el establecimiento de poligonales electrónicas, levantamientos topográficos, redes de nivelación, trazo y replanteo de obras, etc. Asimismo establece redes geodésicas de control en base a posicionamiento satelital de precisión y poligonales de apoyo enlazadas al sistema de coordenadas UTM con datum WGS84 y/o PSAD56. Presta servicios de transformación de coordenadas, control terrestre para aerofotogrametría, georeferenciación de imágenes satelitales, catastro rural y urbano, ejecución de levantamientos topográficos mediante el uso de posicionamiento en tiempo real (GPS RTK).'	
     END DescProyArea	 
      ,[cc_costo] CCostoProyecto
	 -- ,replace([ct_desc], char(13)+char(10),' ') DescContractual	  
	 ,replace((SELECT ct_desc_larga from ERP_TEST..PUB_TA_CCOSTOS where cc_cia = '01' and cc_costo = PUB_TA_CERTIFICADOS.cc_costo), char(13)+char(10),' ') DescContractual
from PUB_TA_CERTIFICADOS  
WHERE coalesce(cc_area,'') <> '' and cc_area <> 'NN'
UNION  
select
 distinct 
 [cc_area] AreaProyecto
  ,case 
		  when [cc_area] = 'TP' then 'CESEL tiene una vasta experiencia en estudios y supervisión de construcción y rehabilitación de obras viales e importante en el sector aeronáutico.  tanto en el Perú como en otros países. Los proyectos desarrollados por CESEL a la fecha superan los 7500 km de carreteras, entre ellas la importante carretera Interoceánica Sur (Tramo 3). Debido a la naturaleza de la geografía peruana, estas obras involucran los más variados terrenos desde los desiertos de la costa, los escarpados y elevados Andes, hasta la lluviosa selva amazónica. En los últimos años CESEL está operando también en la agreste, fuertemente soleada y semiárida región del Chaco, Paraguay, con temperaturas que oscilan entre 46º y -7ºC; y en el altiplano de San Marcos, en Guatemala.'
		  when [cc_area] = 'EN' then 'CESEL tiene una experiencia muy importante en proyectos de generación, transmisión y distribución de energía eléctrica, así como en análisis de sistemas eléctricos. En los primeros años de la década del 80, supervisó las obras civiles y montaje electromecánico de la principal línea de transmisión realizada en el Perú en dicha década, la línea Mantaro - Pachachaca – Callahuanca (Lima) 220 kV, doble circuito y 300 km de longitud. Incluyó tres subestaciones eléctricas de 220 kV, una de ellas encapsulada GIS en SF6 y ubicada a la mayor altitud mundial para este tipo de equipos (4000 msnm). Recientemente es destacable su participación en la línea de interconexión centroamericana 230 kV, 1800 km SIEPAC; así como en los estudios de preoperatividad de la línea de transmisión Mantaro - Caravelí - Montalvo de 500 kV y 750 km de longitud y el diseño definitivo de sus subestaciones.'	
		  when [cc_area] = 'HI' then 'CESEL ha desarrollado una ininterrumpida e intensa actividad tanto en la planificación de recursos hídricos como en la elaboración de estudios y diseños así como en la supervisión de la construcción de grandes obras hidráulicas, abarcando todos los campos de la infraestructura hidráulica. Destaca su actuación en la mayor infraestructura hidroeléctrica diseñada en el Perú en la década del 90: el desarrollo hidroeléctrico San Gabán (450 MW).'	
		  when [cc_area] = 'AA' then 'CESEL siempre ha aplicado criterios ambientales en el desarrollo de sus proyectos, aún antes que en el Perú se establezcan las reglamentaciones específicas.  La gerencia de Asuntos Ambientales desarrolla servicios,en todos los ámbitos principales de actividad humana,instalaciones industriales e infraestructura. Cuenta con autorizaciones vigentes para realizar estudios ambientales en los sectores de agricultura, minería, energía, hidrocarburos, industria, carreteras, edificaciones, aeropuertos y obras portuarias, entre otros'			 
		  when [cc_area] = 'ED' then 'CESEL ha desarrollado proyectos de edificaciones muy importantes y de gran envergadura, como el Hospital Regional de Huancayo de 50 millones de dólares USA de inversión. Actualmente CESEL gerencia la construcción de la nueva ciudad de Morococha con 1050 viviendas y servicios múltiples para 5000 pobladores, una inversión de más de 50 millones de dólares, a más de 4000 m de altitud.'	
		  when [cc_area] = 'MI' then 'CESEL ha participado en los importantes proyectos mineros de Cobriza y Cerro Verde, así como en Yanacocha,Alto Chicama, Pierina, Antamina, Arcata, La Granja, etc.Recientemente ha participado en el desarrollo de la ingenieríabásica y la ingeniería de detalle y gestión de suministro de laAmpliación de la Planta Minera de Toquepala a 100.000 tpd'	
		  when [cc_area] = 'SA' then 'CESEL ha desarrollado estudios integrales de agua potable y alcantarillado de importantes centros urbanos del Perú, tales como Lima, Piura, Cajamarca y Villa El Salvador (750.000 habitantes); así como para la ciudad Puntarenas en Costa Rica; habiendo efectuado el diseño y supervisión de aproximadamente 4000 km de redes de agua potable y alcantarillado, así como de más de 45 plantas de tratamiento de agua y desagüe  '	
		  when [cc_area] = 'PU' then 'CESEL ha desarrollado la mayoría de los puertos fluviales de la amazonía peruana desde mediados de la década del 70, en que diseñó y supervisó la construcción de los puertos de Iquitos, Pucallpa y Yurimaguas. Su participación en los principales puertos marítimos de la costa peruana también ha sido muy importante, destacando el plan maestro de desarrollo al 2025 y el diseño detallado de la ampliación y modernización del Puerto del Callao para una inversión de más de 400 millones de dólares USA. Recientemente ha realizado la supervisión de la construcción y equipamiento del nuevo gran terminal de contenedores en la zona sur  del Puerto del Callao, para naves tipo “Panamax” con un muelle de 650 m y 2 amarraderos. Ha realizado el diseño y supervisión de obra de más de 35 puertos.'	
		  when [cc_area] = 'HP' then 'CESEL desarrolla servicios para la industria petrolera, en lo que se refiere a las instalaciones vinculadas tales como tanques de almacenamiento, tuberías, oleoductos, gasoductos, baterías, estaciones de bombeo, plantas de tratamiento, etc. Ha prestado servicios a las refinerías de La PampillaCESEL desarrolla servicios para la industria petrolera, en lo que se refiere a las instalaciones vinculadas tales como tanques de almacenamiento, tuberías, oleoductos, gasoductos, baterías, estaciones de bombeo, plantas de tratamiento, etc. Ha prestado servicios a las refinerías de La Pampilla y de Talara, entre otras instalaciones importantes. CESEL también desarrolla servicios en el campo de la petroquímica y refinerías para producción de biocombustiblesy de Talara, entre otras instalaciones importantes. CESEL también desarrolla servicios en el campo de la petroquímica y refinerías para producción de biocombustibles'	
		  when [cc_area] = 'MF' then 'CESEL desde fines de la década del 80 la empresa ha estado vinculada con el desarrollo del Metro de Lima. Inicialmente con la supervisión de parte de sus estructuras elevadas. Hace 10 años desarrollando el Estudio de la Red del Metro para las siguientes décadas, incluyendo estudios de demanda de transporte, seleccionando las 5 líneas iniciales, el marco institucional para su operación y administración, elaborando el Anteproyecto e ingeniería de la Línea 1, etc. Actualmente CESEL realiza la supervisión del diseño y de la construcción y montaje de los primeros 22 km del metro, en ruta elevada '	
		  when [cc_area] = 'SL' then 'CESEL ha diseñado y/o supervisado la construcción de un sinnúmero de importantes establecimientos de salud del Perú, como son el Hospital Regional de Huancayo (500 camas), el Hospital General de Belén (400 camas; ampliación y remodelación), Hospital Alberto Sabogal (157 camas) etc, incluyendo todos sus componentes especializados tal como centros quirúrgicos, centro obstétrico y neonatológico, hospitalización, unidad de cuidados intensivos, unidades de diagnóstico por imágenes, radioterapia, etc '	
		  when [cc_area] = 'GT' then 'CESEL realiza estudios de geología orientados a sustentar sus proyectos. Asimismo efectúa una gran diversidad de servicios de exploración geotécnica, tales como: perforación mediante el método de lavado (wash boring), ensayo de penetración estándar (SPT), ensayo de penetración dinámica de cono (CPT), ensayo de penetración dinámica ligera (DPL), auscultación de sondajes (Iwan Auger), registros mediante calicatas y trincheras, controles de compactación, ensayos de permeabilidad in-situ, ensayo de carga directa (Placa), estaciones geomecánicas, ensayo “Tilt Test”, instrumentación y monitoreo de piezómetros y de inclinómetros (para taludes inestables). Ensayos geofísicos: refracción sísmica, Downhole, sondajes eléctricos verticales. Estudios geotécnicos para cimentaciones (superficiales y profundas), túneles, estabilidad de taludes, presas, carreteras, canteras, líneas de transmisión, subestaciones, centrales hidroeléctricas, lagunas de oxidación, etc.'	
		  when [cc_area] = 'CT' then 'CESEL en este rubro desarrolla el establecimiento de poligonales electrónicas, levantamientos topográficos, redes de nivelación, trazo y replanteo de obras, etc. Asimismo establece redes geodésicas de control en base a posicionamiento satelital de precisión y poligonales de apoyo enlazadas al sistema de coordenadas UTM con datum WGS84 y/o PSAD56. Presta servicios de transformación de coordenadas, control terrestre para aerofotogrametría, georeferenciación de imágenes satelitales, catastro rural y urbano, ejecución de levantamientos topográficos mediante el uso de posicionamiento en tiempo real (GPS RTK).'	
     END DescProyArea	 	 
      ,[cc_costo] CCostoProyecto
	  --,replace([ct_desc], char(13)+char(10),' ') DescContractual
	  ,replace((SELECT ct_desc_larga from ERP_TEST..PUB_TA_CCOSTOS where cc_cia = '01' and cc_costo = PUB_TA_CONTRATOS.cc_costo), char(13)+char(10),' ') DescContractual
	   from dbo.PUB_TA_CONTRATOS  
	  WHERE coalesce(cc_area,'') <> '' and cc_area <> 'NN'	  
 UNION  
	  select
	  distinct 
	  [cc_area] AreaProyecto
	  ,case 
		  when [cc_area] = 'TP' then 'CESEL tiene una vasta experiencia en estudios y supervisión de construcción y rehabilitación de obras viales e importante en el sector aeronáutico.  tanto en el Perú como en otros países. Los proyectos desarrollados por CESEL a la fecha superan los 7500 km de carreteras, entre ellas la importante carretera Interoceánica Sur (Tramo 3). Debido a la naturaleza de la geografía peruana, estas obras involucran los más variados terrenos desde los desiertos de la costa, los escarpados y elevados Andes, hasta la lluviosa selva amazónica. En los últimos años CESEL está operando también en la agreste, fuertemente soleada y semiárida región del Chaco, Paraguay, con temperaturas que oscilan entre 46º y -7ºC; y en el altiplano de San Marcos, en Guatemala.'
		  when [cc_area] = 'EN' then 'CESEL tiene una experiencia muy importante en proyectos de generación, transmisión y distribución de energía eléctrica, así como en análisis de sistemas eléctricos. En los primeros años de la década del 80, supervisó las obras civiles y montaje electromecánico de la principal línea de transmisión realizada en el Perú en dicha década, la línea Mantaro - Pachachaca – Callahuanca (Lima) 220 kV, doble circuito y 300 km de longitud. Incluyó tres subestaciones eléctricas de 220 kV, una de ellas encapsulada GIS en SF6 y ubicada a la mayor altitud mundial para este tipo de equipos (4000 msnm). Recientemente es destacable su participación en la línea de interconexión centroamericana 230 kV, 1800 km SIEPAC; así como en los estudios de preoperatividad de la línea de transmisión Mantaro - Caravelí - Montalvo de 500 kV y 750 km de longitud y el diseño definitivo de sus subestaciones.'	
		  when [cc_area] = 'HI' then 'CESEL ha desarrollado una ininterrumpida e intensa actividad tanto en la planificación de recursos hídricos como en la elaboración de estudios y diseños así como en la supervisión de la construcción de grandes obras hidráulicas, abarcando todos los campos de la infraestructura hidráulica. Destaca su actuación en la mayor infraestructura hidroeléctrica diseñada en el Perú en la década del 90: el desarrollo hidroeléctrico San Gabán (450 MW).'	
		  when [cc_area] = 'AA' then 'CESEL siempre ha aplicado criterios ambientales en el desarrollo de sus proyectos, aún antes que en el Perú se establezcan las reglamentaciones específicas.  La gerencia de Asuntos Ambientales desarrolla servicios,en todos los ámbitos principales de actividad humana,instalaciones industriales e infraestructura. Cuenta con autorizaciones vigentes para realizar estudios ambientales en los sectores de agricultura, minería, energía, hidrocarburos, industria, carreteras, edificaciones, aeropuertos y obras portuarias, entre otros'			 
		  when [cc_area] = 'ED' then 'CESEL ha desarrollado proyectos de edificaciones muy importantes y de gran envergadura, como el Hospital Regional de Huancayo de 50 millones de dólares USA de inversión. Actualmente CESEL gerencia la construcción de la nueva ciudad de Morococha con 1050 viviendas y servicios múltiples para 5000 pobladores, una inversión de más de 50 millones de dólares, a más de 4000 m de altitud.'	
		  when [cc_area] = 'MI' then 'CESEL ha participado en los importantes proyectos mineros de Cobriza y Cerro Verde, así como en Yanacocha,Alto Chicama, Pierina, Antamina, Arcata, La Granja, etc.Recientemente ha participado en el desarrollo de la ingenieríabásica y la ingeniería de detalle y gestión de suministro de laAmpliación de la Planta Minera de Toquepala a 100.000 tpd'	
		  when [cc_area] = 'SA' then 'CESEL ha desarrollado estudios integrales de agua potable y alcantarillado de importantes centros urbanos del Perú, tales como Lima, Piura, Cajamarca y Villa El Salvador (750.000 habitantes); así como para la ciudad Puntarenas en Costa Rica; habiendo efectuado el diseño y supervisión de aproximadamente 4000 km de redes de agua potable y alcantarillado, así como de más de 45 plantas de tratamiento de agua y desagüe  '	
		  when [cc_area] = 'PU' then 'CESEL ha desarrollado la mayoría de los puertos fluviales de la amazonía peruana desde mediados de la década del 70, en que diseñó y supervisó la construcción de los puertos de Iquitos, Pucallpa y Yurimaguas. Su participación en los principales puertos marítimos de la costa peruana también ha sido muy importante, destacando el plan maestro de desarrollo al 2025 y el diseño detallado de la ampliación y modernización del Puerto del Callao para una inversión de más de 400 millones de dólares USA. Recientemente ha realizado la supervisión de la construcción y equipamiento del nuevo gran terminal de contenedores en la zona sur  del Puerto del Callao, para naves tipo “Panamax” con un muelle de 650 m y 2 amarraderos. Ha realizado el diseño y supervisión de obra de más de 35 puertos.'	
		  when [cc_area] = 'HP' then 'CESEL desarrolla servicios para la industria petrolera, en lo que se refiere a las instalaciones vinculadas tales como tanques de almacenamiento, tuberías, oleoductos, gasoductos, baterías, estaciones de bombeo, plantas de tratamiento, etc. Ha prestado servicios a las refinerías de La PampillaCESEL desarrolla servicios para la industria petrolera, en lo que se refiere a las instalaciones vinculadas tales como tanques de almacenamiento, tuberías, oleoductos, gasoductos, baterías, estaciones de bombeo, plantas de tratamiento, etc. Ha prestado servicios a las refinerías de La Pampilla y de Talara, entre otras instalaciones importantes. CESEL también desarrolla servicios en el campo de la petroquímica y refinerías para producción de biocombustiblesy de Talara, entre otras instalaciones importantes. CESEL también desarrolla servicios en el campo de la petroquímica y refinerías para producción de biocombustibles'	
		  when [cc_area] = 'MF' then 'CESEL desde fines de la década del 80 la empresa ha estado vinculada con el desarrollo del Metro de Lima. Inicialmente con la supervisión de parte de sus estructuras elevadas. Hace 10 años desarrollando el Estudio de la Red del Metro para las siguientes décadas, incluyendo estudios de demanda de transporte, seleccionando las 5 líneas iniciales, el marco institucional para su operación y administración, elaborando el Anteproyecto e ingeniería de la Línea 1, etc. Actualmente CESEL realiza la supervisión del diseño y de la construcción y montaje de los primeros 22 km del metro, en ruta elevada '	
		  when [cc_area] = 'SL' then 'CESEL ha diseñado y/o supervisado la construcción de un sinnúmero de importantes establecimientos de salud del Perú, como son el Hospital Regional de Huancayo (500 camas), el Hospital General de Belén (400 camas; ampliación y remodelación), Hospital Alberto Sabogal (157 camas) etc, incluyendo todos sus componentes especializados tal como centros quirúrgicos, centro obstétrico y neonatológico, hospitalización, unidad de cuidados intensivos, unidades de diagnóstico por imágenes, radioterapia, etc '	
		  when [cc_area] = 'GT' then 'CESEL realiza estudios de geología orientados a sustentar sus proyectos. Asimismo efectúa una gran diversidad de servicios de exploración geotécnica, tales como: perforación mediante el método de lavado (wash boring), ensayo de penetración estándar (SPT), ensayo de penetración dinámica de cono (CPT), ensayo de penetración dinámica ligera (DPL), auscultación de sondajes (Iwan Auger), registros mediante calicatas y trincheras, controles de compactación, ensayos de permeabilidad in-situ, ensayo de carga directa (Placa), estaciones geomecánicas, ensayo “Tilt Test”, instrumentación y monitoreo de piezómetros y de inclinómetros (para taludes inestables). Ensayos geofísicos: refracción sísmica, Downhole, sondajes eléctricos verticales. Estudios geotécnicos para cimentaciones (superficiales y profundas), túneles, estabilidad de taludes, presas, carreteras, canteras, líneas de transmisión, subestaciones, centrales hidroeléctricas, lagunas de oxidación, etc.'	
		  when [cc_area] = 'CT' then 'CESEL en este rubro desarrolla el establecimiento de poligonales electrónicas, levantamientos topográficos, redes de nivelación, trazo y replanteo de obras, etc. Asimismo establece redes geodésicas de control en base a posicionamiento satelital de precisión y poligonales de apoyo enlazadas al sistema de coordenadas UTM con datum WGS84 y/o PSAD56. Presta servicios de transformación de coordenadas, control terrestre para aerofotogrametría, georeferenciación de imágenes satelitales, catastro rural y urbano, ejecución de levantamientos topográficos mediante el uso de posicionamiento en tiempo real (GPS RTK).'	
     END DescProyArea	    
      ,[cc_costo] CCostoProyecto
	  --,replace([ct_desc], char(13)+char(10),' ') DescContractual
	  ,replace((SELECT ct_desc_larga from ERP_TEST..PUB_TA_CCOSTOS where cc_cia = '01' and cc_costo = PUB_TA_ANEXOS.cc_costo), char(13)+char(10),' ') DescContractual
	   from dbo.PUB_TA_ANEXOS  
	   WHERE coalesce(cc_area,'') <> '' and cc_area <> 'NN'
 UNION  
	  select  distinct 
	  [cc_area] AreaProyecto
	 ,case 
		  when [cc_area] = 'TP' then 'CESEL tiene una vasta experiencia en estudios y supervisión de construcción y rehabilitación de obras viales e importante en el sector aeronáutico.  tanto en el Perú como en otros países. Los proyectos desarrollados por CESEL a la fecha superan los 7500 km de carreteras, entre ellas la importante carretera Interoceánica Sur (Tramo 3). Debido a la naturaleza de la geografía peruana, estas obras involucran los más variados terrenos desde los desiertos de la costa, los escarpados y elevados Andes, hasta la lluviosa selva amazónica. En los últimos años CESEL está operando también en la agreste, fuertemente soleada y semiárida región del Chaco, Paraguay, con temperaturas que oscilan entre 46º y -7ºC; y en el altiplano de San Marcos, en Guatemala.'
		  when [cc_area] = 'EN' then 'CESEL tiene una experiencia muy importante en proyectos de generación, transmisión y distribución de energía eléctrica, así como en análisis de sistemas eléctricos. En los primeros años de la década del 80, supervisó las obras civiles y montaje electromecánico de la principal línea de transmisión realizada en el Perú en dicha década, la línea Mantaro - Pachachaca – Callahuanca (Lima) 220 kV, doble circuito y 300 km de longitud. Incluyó tres subestaciones eléctricas de 220 kV, una de ellas encapsulada GIS en SF6 y ubicada a la mayor altitud mundial para este tipo de equipos (4000 msnm). Recientemente es destacable su participación en la línea de interconexión centroamericana 230 kV, 1800 km SIEPAC; así como en los estudios de preoperatividad de la línea de transmisión Mantaro - Caravelí - Montalvo de 500 kV y 750 km de longitud y el diseño definitivo de sus subestaciones.'	
		  when [cc_area] = 'HI' then 'CESEL ha desarrollado una ininterrumpida e intensa actividad tanto en la planificación de recursos hídricos como en la elaboración de estudios y diseños así como en la supervisión de la construcción de grandes obras hidráulicas, abarcando todos los campos de la infraestructura hidráulica. Destaca su actuación en la mayor infraestructura hidroeléctrica diseñada en el Perú en la década del 90: el desarrollo hidroeléctrico San Gabán (450 MW).'	
		  when [cc_area] = 'AA' then 'CESEL siempre ha aplicado criterios ambientales en el desarrollo de sus proyectos, aún antes que en el Perú se establezcan las reglamentaciones específicas.  La gerencia de Asuntos Ambientales desarrolla servicios,en todos los ámbitos principales de actividad humana,instalaciones industriales e infraestructura. Cuenta con autorizaciones vigentes para realizar estudios ambientales en los sectores de agricultura, minería, energía, hidrocarburos, industria, carreteras, edificaciones, aeropuertos y obras portuarias, entre otros'			 
		  when [cc_area] = 'ED' then 'CESEL ha desarrollado proyectos de edificaciones muy importantes y de gran envergadura, como el Hospital Regional de Huancayo de 50 millones de dólares USA de inversión. Actualmente CESEL gerencia la construcción de la nueva ciudad de Morococha con 1050 viviendas y servicios múltiples para 5000 pobladores, una inversión de más de 50 millones de dólares, a más de 4000 m de altitud.'	
		  when [cc_area] = 'MI' then 'CESEL ha participado en los importantes proyectos mineros de Cobriza y Cerro Verde, así como en Yanacocha,Alto Chicama, Pierina, Antamina, Arcata, La Granja, etc.Recientemente ha participado en el desarrollo de la ingenieríabásica y la ingeniería de detalle y gestión de suministro de laAmpliación de la Planta Minera de Toquepala a 100.000 tpd'	
		  when [cc_area] = 'SA' then 'CESEL ha desarrollado estudios integrales de agua potable y alcantarillado de importantes centros urbanos del Perú, tales como Lima, Piura, Cajamarca y Villa El Salvador (750.000 habitantes); así como para la ciudad Puntarenas en Costa Rica; habiendo efectuado el diseño y supervisión de aproximadamente 4000 km de redes de agua potable y alcantarillado, así como de más de 45 plantas de tratamiento de agua y desagüe  '	
		  when [cc_area] = 'PU' then 'CESEL ha desarrollado la mayoría de los puertos fluviales de la amazonía peruana desde mediados de la década del 70, en que diseñó y supervisó la construcción de los puertos de Iquitos, Pucallpa y Yurimaguas. Su participación en los principales puertos marítimos de la costa peruana también ha sido muy importante, destacando el plan maestro de desarrollo al 2025 y el diseño detallado de la ampliación y modernización del Puerto del Callao para una inversión de más de 400 millones de dólares USA. Recientemente ha realizado la supervisión de la construcción y equipamiento del nuevo gran terminal de contenedores en la zona sur  del Puerto del Callao, para naves tipo “Panamax” con un muelle de 650 m y 2 amarraderos. Ha realizado el diseño y supervisión de obra de más de 35 puertos.'	
		  when [cc_area] = 'HP' then 'CESEL desarrolla servicios para la industria petrolera, en lo que se refiere a las instalaciones vinculadas tales como tanques de almacenamiento, tuberías, oleoductos, gasoductos, baterías, estaciones de bombeo, plantas de tratamiento, etc. Ha prestado servicios a las refinerías de La PampillaCESEL desarrolla servicios para la industria petrolera, en lo que se refiere a las instalaciones vinculadas tales como tanques de almacenamiento, tuberías, oleoductos, gasoductos, baterías, estaciones de bombeo, plantas de tratamiento, etc. Ha prestado servicios a las refinerías de La Pampilla y de Talara, entre otras instalaciones importantes. CESEL también desarrolla servicios en el campo de la petroquímica y refinerías para producción de biocombustiblesy de Talara, entre otras instalaciones importantes. CESEL también desarrolla servicios en el campo de la petroquímica y refinerías para producción de biocombustibles'	
		  when [cc_area] = 'MF' then 'CESEL desde fines de la década del 80 la empresa ha estado vinculada con el desarrollo del Metro de Lima. Inicialmente con la supervisión de parte de sus estructuras elevadas. Hace 10 años desarrollando el Estudio de la Red del Metro para las siguientes décadas, incluyendo estudios de demanda de transporte, seleccionando las 5 líneas iniciales, el marco institucional para su operación y administración, elaborando el Anteproyecto e ingeniería de la Línea 1, etc. Actualmente CESEL realiza la supervisión del diseño y de la construcción y montaje de los primeros 22 km del metro, en ruta elevada '	
		  when [cc_area] = 'SL' then 'CESEL ha diseñado y/o supervisado la construcción de un sinnúmero de importantes establecimientos de salud del Perú, como son el Hospital Regional de Huancayo (500 camas), el Hospital General de Belén (400 camas; ampliación y remodelación), Hospital Alberto Sabogal (157 camas) etc, incluyendo todos sus componentes especializados tal como centros quirúrgicos, centro obstétrico y neonatológico, hospitalización, unidad de cuidados intensivos, unidades de diagnóstico por imágenes, radioterapia, etc '	
		  when [cc_area] = 'GT' then 'CESEL realiza estudios de geología orientados a sustentar sus proyectos. Asimismo efectúa una gran diversidad de servicios de exploración geotécnica, tales como: perforación mediante el método de lavado (wash boring), ensayo de penetración estándar (SPT), ensayo de penetración dinámica de cono (CPT), ensayo de penetración dinámica ligera (DPL), auscultación de sondajes (Iwan Auger), registros mediante calicatas y trincheras, controles de compactación, ensayos de permeabilidad in-situ, ensayo de carga directa (Placa), estaciones geomecánicas, ensayo “Tilt Test”, instrumentación y monitoreo de piezómetros y de inclinómetros (para taludes inestables). Ensayos geofísicos: refracción sísmica, Downhole, sondajes eléctricos verticales. Estudios geotécnicos para cimentaciones (superficiales y profundas), túneles, estabilidad de taludes, presas, carreteras, canteras, líneas de transmisión, subestaciones, centrales hidroeléctricas, lagunas de oxidación, etc.'	
		  when [cc_area] = 'CT' then 'CESEL en este rubro desarrolla el establecimiento de poligonales electrónicas, levantamientos topográficos, redes de nivelación, trazo y replanteo de obras, etc. Asimismo establece redes geodésicas de control en base a posicionamiento satelital de precisión y poligonales de apoyo enlazadas al sistema de coordenadas UTM con datum WGS84 y/o PSAD56. Presta servicios de transformación de coordenadas, control terrestre para aerofotogrametría, georeferenciación de imágenes satelitales, catastro rural y urbano, ejecución de levantamientos topográficos mediante el uso de posicionamiento en tiempo real (GPS RTK).'	
     END DescProyArea	 
      ,[cc_costo] CCostoProyecto
	  --,replace([ct_desc], char(13)+char(10),' ') DescContractual
	 ,replace((SELECT ct_desc_larga from ERP_TEST..PUB_TA_CCOSTOS where cc_cia = '01' and cc_costo = PUB_TA_ADENDAS.cc_costo), char(13)+char(10),' ') DescContractual
	   from dbo.PUB_TA_ADENDAS  
	   WHERE coalesce(cc_area,'') <> '' and cc_area <> 'NN'

order by AreaProyecto, cc_costo desc


--file://lim-fs01/CERTCON/1.CONTRATOS/2022-2023/230100_CONTRATO_Programa_Rehabilitaci%C3%B3n_Mejoramiento_Aeropuerto_Chachapoyas.pdf


